// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAywDnmul0nrRXe1kDF3oDbl1ip3B-RkPg',
    appId: '1:169131297810:web:e8cbbbc83ed69c85869ccb',
    messagingSenderId: '169131297810',
    projectId: 'chatapp-631fa',
    authDomain: 'chatapp-631fa.firebaseapp.com',
    storageBucket: 'chatapp-631fa.appspot.com',
    measurementId: 'G-ZTL1HLFL7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDroJQvLJAf4CuDh5xu_VkcJgiYp9QXgXc',
    appId: '1:169131297810:android:dbaf57b56c27cb42869ccb',
    messagingSenderId: '169131297810',
    projectId: 'chatapp-631fa',
    storageBucket: 'chatapp-631fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KygwNWbPywfQ0Tvql6pD-A4bUrKxNoU',
    appId: '1:169131297810:ios:a7b8711f61f064c8869ccb',
    messagingSenderId: '169131297810',
    projectId: 'chatapp-631fa',
    storageBucket: 'chatapp-631fa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KygwNWbPywfQ0Tvql6pD-A4bUrKxNoU',
    appId: '1:169131297810:ios:a7b8711f61f064c8869ccb',
    messagingSenderId: '169131297810',
    projectId: 'chatapp-631fa',
    storageBucket: 'chatapp-631fa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
